import { Header, SideNav } from '../components';
import { ThemeProvider } from '../providers';
import './global.css';

export const metadata = {
  title: 'Welcome to dashboard',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className="flex min-h-screen dark:bg-base-100 dark:text-base-content">
          <SideNav />
          <div className="flex-1">
            <Header />
            <main>{children}</main>
          </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
